### ISSUE TITLE
Deck history does not show card counts

### ISSUE THREAD

**Issue by Dragas** [shaobaili3/LoR_Master#28]
When you play against another player, you're presented with their deck history from last 20 matches. The said decklist does not include amounts of particular cards. Instead only the cards themselves are shown. Surprisingly you still are capable of extracting the decklist code, which does contain the amounts of cards.
![image](https://user-images.githubusercontent.com/6078508/148699291-a6444d3f-0da4-477c-9f48-5b6538e5795e.png)
![image](https://user-images.githubusercontent.com/6078508/148699354-447671f7-648b-4b13-aede-c7382a48d9e7.png)

Running the application in debugging mode does show that there should be something there, but my guess is that the deck decoder incorrectly extracts the amounts, causing the value to be undefined and in turn not rendered by vue
![image](https://user-images.githubusercontent.com/6078508/148699408-8d1ee1cd-992a-46bb-b0a7-1ebc04044272.png)

In addition, looking for file in the repository called deck.html (or similar vue components) does not seem to yield any results. Where is the deck tracker UI interface?

**Comment by painttist** [comment]
Hi! Wow that is some dedication to debugging. You must be a very experienced developer. So regarding the count, it is actually intentionally left out because Riot emailed us saying it is on the verge of providing too much advantage, so we kind of settled on this middle ground to make it at least slightly header to gain an unfair advantage. But yeah, this is basically a toggle of v-if. Hopefully we can figure out a more elegant solution later on.

**Comment by Dragas** [comment]
Shame, really. Because I still can get the same information by extracting the deck code via copy deck button. But this does not solve the issue where Riot API itself exposes the deck codes for previous matches.
