### ISSUE TITLE
Docking behaviour with vertical task bar

### ISSUE THREAD

**Issue by Makstuff** [shaobaili3/LoR_Master#30]
Due to personal preference, I have my Windows task bar set to vertical (on the left side of the screen). The tracker seems to be coded to dock to the taskbar edge instead of the screen edge, so I can't place the tracker on the edge of the screen when playing in full screen, it will always leave the task bar width as a gap between tracker and screen edge.

**Comment by painttist** [comment]
I have never tried vertical bar before, so I tried it. And now I totally understand what you mean. Bad news first, this is probably not going to be fixed because it is a default Windows behavior, and unfortunately to me knowledge, the framework we use (Electron) doesn't have great support for customizing when and where to dock.

The good news is that whole top bar is draggable, so if you start dragging from the very right edge of the tracker, there is just enough width to position it right near the edge. You can also always make the tracker wider, position it, and resize it back down. Yeah this is probably not the perfect solution but you should only need to do this once and the position will be recorded. Hope this helps!

Later on, we will probably add a way to manually position the tracker through numbers in the settings page. This way you can avoid having to drag it around so it will not dock.

Thanks for your feedback! Hope you have some good games 🥂
