### ISSUE TITLE
Personal Deck win rate vs archetypes

### ISSUE THREAD

**Issue by lmeilibr** [shaobaili3/LoR_Master#6]
This is a feature that lor guardians and mobalytics doesnt have and could be a great differential for LoR_Master.

I need to understand more about the code base to know how to fetch the data, but the output would be something like:

Mydeck 55% vs Azir/Irelia
Mydeck 45% vs Fiona
Etc...

**Comment by shaobaili3** [comment]
I agree. This is a pretty cool feature, we will add this in the future.

Currently, LMT only pulls data via Riot API and provides stats with visualizations. The maximum number of matches is 20 limited by API, so it hard to present stats like this due to missing data. The private database will be built after the production release(v1.0) to store all matches. More stats like this will be able to present.

You can have a try based on the limited data. Every match data is processed in Models -> player.py -> inspectPlayer function.  The function is too long. I will refactor it and add more comments to help you understand.
